### ISSUE TITLE
Adding the Code of Conduct

### ISSUE THREAD

**Issue by KamalDGRT** [DSC-SIST/Project-Development#1]
### AIM

Create Code of Conduct to let new Contributors give insight regarding the same.

### Features

- Add a `CODE_OF_CONDUCT.md` to allow new users to let new Contributors give insight regarding the same

**Comment by Venkatesh-tech** [comment]
Can you assign this issue to me...

**Comment by KamalDGRT** [comment]
Good work @Venkatesh-tech :tada:
