### ISSUE TITLE
[Feature] Auto assign using /assign command

### ISSUE THREAD

**Issue by KamalDGRT** [DSC-SIST/Project-Development#14]
### Objective :pushpin:

To let the contributor assign themselves to an issue by just commenting `/assgin`

**Comment by Venkatesh-tech** [comment]
Can you assign this issue to me...

**Comment by KamalDGRT** [comment]
Done! :+1:

**Comment by KamalDGRT** [comment]
Good Work @Venkatesh-tech :tada:

**Comment by Venkatesh-tech** [comment]
Thank you bhai for your mentorship

**Comment by KamalDGRT** [comment]
Happy to help you!
