### ISSUE TITLE
[Feature] Adding the Contributors to a separate file

### ISSUE THREAD

**Issue by KamalDGRT** [DSC-SIST/Project-Development#16]
### Objective :pushpin:

To simplify the process of adding the names of the contributors along with their GitHub profile.

### Features to be added / modified :ballot_box_with_check:

- Use `allcontributorsbot` to automate this process

**Comment by aditijhaa9901** [comment]
I would like to work on this.

**Comment by KamalDGRT** [comment]
From now on, you can comment `/assign` on an issue that you would like to work on.
The bot will assign it to you.
