### ISSUE TITLE
[Doc] Make Contributors Guideline

### ISSUE THREAD

**Issue by KamalDGRT** [DSC-SIST/Project-Development#9]
### Objective :pushpin:

Create Contributors Guideline to help new Contributors get started with this Project.

### Features to be added / modified :ballot_box_with_check:

- Add a `CONTRIBUTING.md` to allow new users to get started with knowing how to contribute.
- Add Screenshots wherever possible.
- Mention the way to set the project locally in the PC
- Add the basic information about creating Issues, Pull Requests and Branching.
- Mention tutorials related to Git and GitHub to help them better understand.

**Comment by manojtummala** [comment]
I will take this issue

**Comment by KamalDGRT** [comment]
Good work @manojtummala :tada:
